version: 2.1

executors:
  node-docker:
    docker:
      - image: cimg/node:16.14.2
    resource_class: small

commands:
  install-dependencies:
    description: 'Install dependencies with pnpm'
    steps:
      - run:
          name: Install pnpm
          command: sudo npm install --global pnpm

      - run:
          name: Install Dependencies
          command: pnpm install

  login-docker:
    description: "Log into Docker Hub"
    steps:
      - run:
          command: docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_KEY

jobs:
  test:
    executor: node-docker
    steps:
      - checkout
      - install-dependencies
      - run:
          name: "Run tests"
          command: pnpm run test

  deploy:
    executor: node-docker
    steps:
      - setup_remote_docker:
          version: 20.10.6
          docker_layer_caching: false
      - checkout
      - login-docker
      - run:
          name: "Build and push image"
          command: |
            docker build -t pakut2/battlesnake:latest .
            docker push pakut2/battlesnake:latest

workflows:
  version: 2
  main:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - main
