version: 2.1

executors:
  node-docker:
    docker:
      - image: cimg/node:16.14.2
    resource_class: small

commands:
  install-npm-dependencies:
    description: 'Installs dependencies with pnpm'
    steps:
      - run:
          name: Install pnpm
          command: |
            sudo npm install --global pnpm

      - restore_cache:
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}

      - run:
          name: Install Dependencies
          command: pnpm install --frozen-lockfile

      - save_cache:
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - ~/.pnpm-store

  login-docker:
    description: "Log into Docker Hub"
    steps:
      - run:
          command: docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_KEY

jobs:
  build:
    executor: node-docker
    steps:
      - checkout
      - install-npm-dependencies
      - run:
          name: "Build project"
          command: pnpm run build

  test:
    executor: node-docker
    steps:
      - checkout
      - install-npm-dependencies
      - run:
          name: "Run tests"
          command: pnpm run test

  build-image:
    executor: node-docker
    steps:
      - setup_remote_docker:
          version: 20.10.6
          docker_layer_caching: false
      - checkout
      - login-docker
      - run:
          name: "Build and push image"
          command: |
            docker build -t pakut2/battlesnake:latest .
            docker push pakut2/battlesnake:latest

workflows:
  version: 2
  main:
    jobs:
      - build
      - test
      - build-image